export const productsFR = [
  'Baguette',
  'Pâtes',
  'Ketchup',
  'Pizza',
  'Viennoiserie',
  'Beurre',
  'Gruyère râpé',
  'Lait',
  'Eau minérale',
  'Cornichons',
  'Oeufs',
  'Pain de mie',
  'Chocolat',
  'Nouilles',
  'Fromage',
  'Chips',
  'Café',
  'Jambon',
  'Cacao',
  'Citron',
  'Champignons',
  'Bière',
  'Pomme de terre',
  'Steak haché',
  'Sucre',
  'Dentifrice',
  'Brosse à dents',
  'Gants',
  'Nettoyant',
  'Lessive',
  'Liquide vaisselle',
  'Nettoyant sol',
  'Savon',
  'Adoucissant',
  'Éponge',
  'Papier toilette',
  'Nettoyant WC',
  'Mouchoirs',
  'Essuie-tout',
  'Thé',
  'Haricots verts',
  'Oignon',
  'Soda',
  'Mayonnaise',
  'Frites',
  'Crème fraîche',
  'Pâte à tarte',
  'Confiture',
  'Miel',
  'Riz',
  'Gâteaux',
  'Shampooing',
  'Gel douche',
  'Yahout',
  'Pâte à tartiner',
  'Céréales',
  'Apéritifs',
  'Sauce tomate',
  'Vin',
  'Cotons-tige',
  'Lingettes',
  'Couches',
  'Compotes',
  'Sacs poubelle',
  'Poisson',
  'Farine',
  'Serviettes / Tampons',
];
